### ISSUE TITLE
Having to restart after pressing :generate" if there is any error in the code?

### ISSUE THREAD

**Issue by bes827** [jcrodriguez1989/shinyWYSIWYG#2]
Hello
thanks for the great app. 
I noted that the app disconnects from the server if I press generate and there is any mistake in the code, then I have to restart all over. One way is to save the work and load it if it gets disconnected but is there an easier way to avoid that? 

thanks again

**Comment by jcrodriguez1989** [comment]
Hi @bes828 !
What kind of _mistake in the code_? Could you tell me an easy step-through to reproduce your issue?
thanks!

**Comment by bes827** [comment]
thanks for the quick reply
I am just trying to write a simple app to add numbers (please see the first 2 screen shots).
there are probably some errors in the code. when I click generate, I get an error saying disconnected from server

![image](https://user-images.githubusercontent.com/60957778/97730611-771bb880-1aaa-11eb-999f-092fa5ee6d0a.png)


![image](https://user-images.githubusercontent.com/60957778/97730846-c5c95280-1aaa-11eb-8d06-60d6ddac4557.png)

![image](https://user-images.githubusercontent.com/60957778/97730869-ccf06080-1aaa-11eb-9100-6cc99e0c66b7.png)

**Comment by jcrodriguez1989** [comment]
thanks for your finding!
Could you try it now? :)

**Comment by bes827** [comment]
now I actually do not see the cursor to drag the elements in the UI. Everything looks the same but the mouse cursor does not allow adding elements such as numeric input into the canvas. 

thanks really for this app, I believe it is very useful for people like me that do not have strong experience with shiny yet, it allows deployment of (at least) simple apps with minimal effort. plus it teaches how shiny works in a nice way. would you consider posting few more examples? or even couple of short videos?

**Comment by jcrodriguez1989** [comment]
thanks for your time,
the last seemed to be a really strange issue. I think it has been solved now. I would really appreciate if you could test it again :+1: .

this app was mainly built to be used as a tool to learn the basics about shiny apps development. I would highly recommend you to use it just for this purpose, and meanwhile, read documentation or tutorials to learn to build powerful shiny apps :)
